Repository hlxsites/prisma-cloud-docs, pull requests merged in 2023-11, with the labels that each got.

#205 update for 116255
  docs/en/enterprise-edition/content-collections/administration/configure-iam-security/enable-iam-security.adoc
Labels: documentation

#196 [RN] - 23.11.1 RN updates - Nov 3rd Publish
  docs/en/classic/cspm-admin-guide/connect-your-cloud-platform-to-prisma-cloud/onboard-gcp/prerequisites-to-onboard-gcp.adoc
  docs/en/classic/cspm-admin-guide/prisma-cloud-compliance/compliance-dashboard.adoc
  docs/en/enterprise-edition/content-collections/compliance/compliance-standards.adoc
  docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-gcp/prerequisites-to-onboard-gcp.adoc
  docs/en/enterprise-edition/rn/book.yml
  docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
  docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
  docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-source.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2023/features-introduced-in-2023.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2023/features-introduced-in-november-2023.adoc
Labels: documentation, ready-to-be-merged

#217 [AWS] RLP-113615 AWS EventBridge updates
  docs/en/classic/cspm-admin-guide/connect-your-cloud-platform-to-prisma-cloud/onboard-aws/configure-audit-logs.adoc
  docs/en/enterprise-edition/content-collections/connect/collection-connect.yml
  docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-aws/configure-audit-logs.adoc
  docs/en/enterprise-edition/content-collections/connect/connect.adoc
Labels: documentation, ready-to-be-merged

#226 [Compute LookAhead]: Remove O'Neal announcement
  docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
Labels: ready-to-be-merged

#236 [Runtime Security]: Add deploy defender in GCR file
  docs/en/compute-edition/30/admin-guide/install/deploy-defender/app-embedded/deploy-app-embedded-defender-gcr.adoc
Labels: documentation

#243 minor text updates
  docs/en/classic/rql-reference/rql-reference/operators.adoc
Labels: documentation, do-not-merge

#246 [Runtime Security]Update Agentless Scans duration
  docs/en/classic/compute-admin-guide/agentless-scanning/agentless-scanning-modes.adoc
  docs/en/compute-edition/31/admin-guide/agentless-scanning/agentless-scanning-modes.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/agentless-scanning/agentless-scanning-modes.adoc
Labels: documentation, enhancement

#247 Update look-ahead for ONeal
  docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
Labels: O'Neal

#227 [AppSec] Remove instances of Build Integrity from Classic
  docs/en/classic/appsec-admin-guide/_graphics/enfor-1.png
  docs/en/classic/appsec-admin-guide/_graphics/enfor-10.png
  docs/en/classic/appsec-admin-guide/_graphics/enfor-11.png
  docs/en/classic/appsec-admin-guide/_graphics/enfor-12.png
  docs/en/classic/appsec-admin-guide/_graphics/enfor-14.png
  docs/en/classic/appsec-admin-guide/_graphics/enfor-2.png
  docs/en/classic/appsec-admin-guide/_graphics/enfor-21.png
  docs/en/classic/appsec-admin-guide/_graphics/enfor-22.png
  docs/en/classic/appsec-admin-guide/_graphics/enfor-3.png
  docs/en/classic/appsec-admin-guide/_graphics/enfor-4.png
  docs/en/classic/appsec-admin-guide/_graphics/enfor-5.png
  docs/en/classic/appsec-admin-guide/_graphics/enfor-6.png
  docs/en/classic/appsec-admin-guide/_graphics/enfor-7.png
  docs/en/classic/appsec-admin-guide/_graphics/enfor-8.png
  docs/en/classic/appsec-admin-guide/_graphics/enfor.png
  docs/en/classic/appsec-admin-guide/risk-prevention/code/enforcement.adoc
  docs/en/classic/appsec-admin-guide/risk-prevention/code/monitor-fix-issues-in-scan.adoc
Labels: documentation
