Repository hlxsites/prisma-cloud-docs, pull requests merged in 2023-12, with the labels that each got.

#266 [Dashboard - UVE]: Vulnerabilities count updates
  docs/en/enterprise-edition/content-collections/dashboards/dashboards-vulnerabilities.adoc
Labels: documentation

#255 [AppSec Policy Ref] Fix issues from DITA
  docs/en/enterprise-edition/policy-reference/azure-policies/azure-general-policies/azr-general-163.adoc
  docs/en/enterprise-edition/policy-reference/azure-policies/azure-general-policies/azr-general-164.adoc
  docs/en/enterprise-edition/policy-reference/azure-policies/azure-general-policies/azr-general-166.adoc
  docs/en/enterprise-edition/policy-reference/azure-policies/azure-general-policies/azr-general-167.adoc
  docs/en/enterprise-edition/policy-reference/azure-policies/azure-general-policies/azr-general-170.adoc
  docs/en/enterprise-edition/policy-reference/azure-policies/azure-general-policies/azr-general-172.adoc
  docs/en/enterprise-edition/policy-reference/azure-policies/azure-general-policies/azr-general-173.adoc
  docs/en/enterprise-edition/policy-reference/azure-policies/azure-general-policies/azr-general-175.adoc
  docs/en/enterprise-edition/policy-reference/azure-policies/azure-general-policies/azr-general-177.adoc
  docs/en/enterprise-edition/policy-reference/azure-policies/azure-general-policies/azr-general-178.adoc
  docs/en/enterprise-edition/policy-reference/azure-policies/azure-general-policies/azr-general-179.adoc
  docs/en/enterprise-edition/policy-reference/azure-policies/azure-general-policies/azr-general-180.adoc
  docs/en/enterprise-edition/policy-reference/azure-policies/azure-general-policies/azr-general-186.adoc
  docs/en/enterprise-edition/policy-reference/azure-policies/azure-general-policies/azr-general-187.adoc
  docs/en/enterprise-edition/policy-reference/azure-policies/azure-general-policies/azr-general-188.adoc
  docs/en/enterprise-edition/policy-reference/azure-policies/azure-general-policies/azr-general-196.adoc
  docs/en/enterprise-edition/policy-reference/azure-policies/azure-general-policies/azr-general-199.adoc
  docs/en/enterprise-edition/policy-reference/azure-policies/azure-general-policies/azr-general-201.adoc
  docs/en/enterprise-edition/policy-reference/azure-policies/azure-general-policies/azr-general-206.adoc
  docs/en/enterprise-edition/policy-reference/azure-policies/azure-general-policies/azr-general-208.adoc
  docs/en/enterprise-edition/policy-reference/azure-policies/azure-general-policies/azr-general-209.adoc
  docs/en/enterprise-edition/policy-reference/azure-policies/azure-general-policies/azr-general-211.adoc
  docs/en/enterprise-edition/policy-reference/azure-policies/azure-general-policies/azr-general-212.adoc
  docs/en/enterprise-edition/policy-reference/azure-policies/azure-general-policies/azr-general-214.adoc
  docs/en/enterprise-edition/policy-reference/azure-policies/azure-general-policies/azr-general-3.adoc
  docs/en/enterprise-edition/policy-reference/azure-policies/azure-general-policies/azure-general-policies.adoc
  docs/en/enterprise-edition/policy-reference/azure-policies/azure-iam-policies/azr-iam-176.adoc
  docs/en/enterprise-edition/policy-reference/azure-policies/azure-iam-policies/azr-iam-181.adoc
  docs/en/enterprise-edition/policy-reference/azure-policies/azure-iam-policies/azr-iam-184.adoc
  docs/en/enterprise-edition/policy-reference/azure-policies/azure-iam-policies/azr-iam-191.adoc
  docs/en/enterprise-edition/policy-reference/azure-policies/azure-iam-policies/azr-iam-192.adoc
  docs/en/enterprise-edition/policy-reference/book.yml
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/azure-repo-cicd-pipeline-policies/azure-repo-pr-review-notrequired-merge.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/azure-repo-cicd-pipeline-policies/azure-repo-requestors-self-approve-pr-defaultbranch.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/circleci-cicd-pipeline-policies/circleci-vulnerable-cmnd-injection.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/github-cicd-pipeline-policies/gh-code-owners-review-not-required-tomerge.adoc
  docs/en/enterprise-edition/policy-reference/sast-policies/java-policies/sast-policy-162.adoc
Labels: documentation

#234 Nov SAST policies
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/azure-repo-cicd-pipeline-policies/azure-repo-pr-review-notrequired-merge.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/azure-repo-cicd-pipeline-policies/azure-repo-requestors-self-approve-pr-defaultbranch.adoc
  docs/en/enterprise-edition/policy-reference/sast-policies/javascript-policies/sast-javascript-policy-index.adoc
  docs/en/enterprise-edition/policy-reference/sast-policies/javascript-policies/sast-policy-174.adoc
  docs/en/enterprise-edition/policy-reference/sast-policies/javascript-policies/sast-policy-176.adoc
  docs/en/enterprise-edition/policy-reference/sast-policies/javascript-policies/sast-policy-177.adoc
  docs/en/enterprise-edition/policy-reference/sast-policies/javascript-policies/sast-policy-178.adoc
  docs/en/enterprise-edition/policy-reference/sast-policies/javascript-policies/sast-policy-42.adoc
  docs/en/enterprise-edition/policy-reference/sast-policies/python-policies/sast-policy-173.adoc
  docs/en/enterprise-edition/policy-reference/sast-policies/python-policies/sast-policy-175.adoc
  docs/en/enterprise-edition/policy-reference/sast-policies/python-policies/sast-python-policy-index.adoc
Labels: do-not-merge

#262 customer note update
  docs/en/enterprise-edition/content-collections/alerts/create-an-alert-rule-cloud-infrastructure.adoc
Labels: documentation, do-not-merge

#277 Azure fixes
  docs/en/enterprise-edition/content-collections/administration/configure-iam-security/integrate-prisma-cloud-with-idp-services.adoc
  docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-your-azure-account/connect-azure-account.adoc
  docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-your-azure-account/microsoft-azure-apis-ingested-by-prisma-cloud.adoc
Labels: documentation, do-not-merge

#295 [Runtime Security] O'Neal Update 1 Look Ahead
  docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
Labels: O'Neal Update 1

#292 App sec jb transporter
  docs/en/enterprise-edition/content-collections/_graphics/application-security/docker-connectivity-main2.0.png
  docs/en/enterprise-edition/content-collections/_graphics/application-security/docker-run-image1.1.png
  docs/en/enterprise-edition/content-collections/_graphics/application-security/legend-blue.png
  docs/en/enterprise-edition/content-collections/_graphics/application-security/legend-blue1.1.png
  docs/en/enterprise-edition/content-collections/_graphics/application-security/legend-connectivity.png
  docs/en/enterprise-edition/content-collections/_graphics/application-security/legend-green.png
  docs/en/enterprise-edition/content-collections/_graphics/application-security/legend-red.png
  docs/en/enterprise-edition/content-collections/_graphics/application-security/select-transporter1.1.png
  docs/en/enterprise-edition/content-collections/_graphics/application-security/select-transporter1.2.png
  docs/en/enterprise-edition/content-collections/_graphics/application-security/transport-health-check1.1.png
  docs/en/enterprise-edition/content-collections/_graphics/application-security/transporter-connectivity-browser-all-2.0.png
  docs/en/enterprise-edition/content-collections/_graphics/application-security/transporter-connectivity-docker-proxy-2.0.png
  docs/en/enterprise-edition/content-collections/_graphics/application-security/transporter-connectivity-k8s-main-2.0.png
  docs/en/enterprise-edition/content-collections/_graphics/application-security/transporter-connectivity-k8s-proxy-2.0.png
  docs/en/enterprise-edition/content-collections/_graphics/application-security/transporter-docker-connectivity-log2.2.png
  docs/en/enterprise-edition/content-collections/_graphics/application-security/transporter-int-wiz-mng-int.png
  docs/en/enterprise-edition/content-collections/_graphics/application-security/transporter-k8s-usecases.png
  docs/en/enterprise-edition/content-collections/_graphics/application-security/transporter-trusted-ipaddresses.png
  docs/en/enterprise-edition/content-collections/_graphics/application-security/transporter-verify-connectivity-ui1.1.png
  docs/en/enterprise-edition/content-collections/_graphics/application-security/ui-wizard-deploy-client.png
  docs/en/enterprise-edition/content-collections/application-security/collection-application-security.yml
  docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-gitlab-selfmanaged.adoc
  docs/en/enterprise-edition/content-collections/application-security/get-started/manage-network-tunnel/deploy-transporter-docker.adoc
  docs/en/enterprise-edition/content-collections/application-security/get-started/manage-network-tunnel/deploy-transporter-helmcharts.adoc
  docs/en/enterprise-edition/content-collections/application-security/get-started/manage-network-tunnel/manage-network-tunnel.adoc
  docs/en/enterprise-edition/content-collections/application-security/get-started/manage-network-tunnel/select-transporter-domain-consistency.adoc
  docs/en/enterprise-edition/content-collections/application-security/get-started/manage-network-tunnel/transporter-connectivity-overview.adoc
  docs/en/enterprise-edition/content-collections/book.yml
Labels: documentation, ready-to-be-merged
