Repository hlxsites/prisma-cloud-docs, pull requests merged in 2023-10, with the labels that each got.

#153 Rn replacements
  docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
  docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-cspm-release-information/features-introduced-in-april-2023.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-cspm-release-information/features-introduced-in-august-2023.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-cspm-release-information/features-introduced-in-february-2023.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-cspm-release-information/features-introduced-in-january-2023.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-cspm-release-information/features-introduced-in-july-2023.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-cspm-release-information/features-introduced-in-june-2023.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-cspm-release-information/features-introduced-in-march-2023.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-cspm-release-information/features-introduced-in-may-2023.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-cspm-release-information/features-introduced-in-october-2023.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-cspm-release-information/features-introduced-in-september-2023.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2023/features-introduced-in-october-2023.adoc
Labels: documentation, ready-to-be-merged

#160 updated sheets path, fixed xrefs
  docs/en/classic/cspm-admin-guide/connect-your-cloud-platform-to-prisma-cloud/onboard-aws/aws-apis-ingested-by-prisma-cloud.adoc
  docs/en/classic/cspm-admin-guide/connect-your-cloud-platform-to-prisma-cloud/onboard-gcp/gcp-apis-ingested-by-prisma-cloud.adoc
  docs/en/classic/cspm-admin-guide/connect-your-cloud-platform-to-prisma-cloud/onboard-your-alibaba-account/alibaba-apis-ingested-by-prisma-cloud.adoc
  docs/en/classic/cspm-admin-guide/connect-your-cloud-platform-to-prisma-cloud/onboard-your-azure-account/microsoft-azure-apis-ingested-by-prisma-cloud.adoc
  docs/en/classic/cspm-admin-guide/connect-your-cloud-platform-to-prisma-cloud/onboard-your-oci-account/oci-apis-ingested-by-prisma-cloud.adoc
  docs/en/classic/cspm-admin-guide/manage-prisma-cloud-administrators/prisma-cloud-admin-permissions.adoc
  docs/en/enterprise-edition/content-collections/connect/connect-code-and-build-providers.adoc
  docs/en/enterprise-edition/content-collections/connect/connect-image-registries.adoc
  docs/en/enterprise-edition/content-collections/connect/deploy-defenders.adoc
  docs/en/enterprise-edition/content-collections/search-and-investigate/asset-queries/asset-queries.adoc
Labels: ready-to-be-merged

#166 [Darwin]: All collections - Docs fixes
  docs/en/enterprise-edition/content-collections/_graphics/runtime-security/new-registry-add-and-scan.png
  docs/en/enterprise-edition/content-collections/alerts/create-an-alert-rule-cloud-infrastructure.adoc
  docs/en/enterprise-edition/content-collections/alerts/send-prisma-cloud-alert-notifications-to-third-party-tools.adoc
  docs/en/enterprise-edition/content-collections/alerts/suppress-alerts-for-prisma-cloud-anomaly-policies.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/vulnerability-management/scan-custom-vulnerabilities.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/vulnerability-management/vulnerability-management-policies.adoc
  docs/en/enterprise-edition/content-collections/search-and-investigate/search-and-investigate.adoc
Labels: documentation

#172 [App Sec collection] Merge Requested
  docs/en/enterprise-edition/content-collections/_graphics/application-security/github-auth-prisma1.1.png
  docs/en/enterprise-edition/content-collections/_graphics/application-security/github-select-repos1.1.png
  docs/en/enterprise-edition/content-collections/_graphics/application-security/gitlab-auth1.1.png
  docs/en/enterprise-edition/content-collections/_graphics/application-security/non-default-branch-menu1.1.png
  docs/en/enterprise-edition/content-collections/_graphics/application-security/non-default-branch-select.png
  docs/en/enterprise-edition/content-collections/application-security/familiarize-application-security.adoc
  docs/en/enterprise-edition/content-collections/application-security/get-started/application-security-settings/application-security-settings.adoc
  docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/add-private-registries.adoc
  docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/ci-cd-runs/add-aws-codebuild.adoc
  docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/ci-cd-runs/add-checkov.adoc
  docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/ci-cd-runs/add-circleci.adoc
  docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/ci-cd-runs/add-github-actions.adoc
  docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/ci-cd-runs/add-jenkins.adoc
  docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/ci-cd-systems/add-circleci-cicd-system.adoc
  docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/ci-cd-systems/add-jenkins-cicd-system.adoc
  docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-azurerepos.adoc
  docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-bitbucket-server.adoc
  docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-bitbucket.adoc
  docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-github-server.adoc
  docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-github.adoc
  docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-gitlab-selfmanaged.adoc
  docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-gitlab.adoc
  docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/code-repositories.adoc
  docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/connect-code-and-build-providers.adoc
  docs/en/enterprise-edition/content-collections/application-security/get-started/get-started.adoc
  docs/en/enterprise-edition/content-collections/application-security/get-started/manage-network-tunnel/deploy-transporter-docker.adoc
  docs/en/enterprise-edition/content-collections/application-security/get-started/non-default-branch-scan.adoc
  docs/en/enterprise-edition/content-collections/application-security/risk-management/ci-cd-risks.adoc
  docs/en/enterprise-edition/content-collections/application-security/risk-management/monitor-and-manage-code-build/monitor-and-manage-code-build.adoc
  docs/en/enterprise-edition/content-collections/application-security/risk-management/monitor-and-manage-code-build/monitor-code-build-issues.adoc
  docs/en/enterprise-edition/content-collections/application-security/risk-management/risk-management.adoc
  docs/en/enterprise-edition/content-collections/application-security/visibility/repositories.adoc
Labels: ready-to-be-merged

#173 [AppSec] Migrate PR#1655 from PCRepo
  docs/en/enterprise-edition/content-collections/_graphics/application-security/notifications-ci-cd-security.png
  docs/en/enterprise-edition/content-collections/_graphics/application-security/notifications-code-security.png
  docs/en/enterprise-edition/content-collections/application-security/get-started/application-security-settings/application-security-settings.adoc
  docs/en/enterprise-edition/content-collections/application-security/get-started/manage-roles-permissions.adoc
  docs/en/enterprise-edition/content-collections/application-security/risk-management/monitor-and-manage-code-build/drift-detection.adoc
  docs/en/enterprise-edition/content-collections/application-security/risk-management/monitor-and-manage-code-build/secrets-scanning.adoc
  docs/en/enterprise-edition/content-collections/application-security/risk-management/monitor-and-manage-code-build/software-composition-analysis/software-composition-analysis.adoc
  docs/en/enterprise-edition/content-collections/dashboards/dashboards-application-security.adoc
Labels: documentation, enhancement, ready-to-be-merged

#184 updated screenshots
  docs/en/enterprise-edition/content-collections/_graphics/search-and-investigate/background-jobs-1.png
  docs/en/enterprise-edition/content-collections/_graphics/search-and-investigate/build-modify-1.png
  docs/en/enterprise-edition/content-collections/_graphics/search-and-investigate/build-modify-2.png
  docs/en/enterprise-edition/content-collections/_graphics/search-and-investigate/build-modify-3.png
  docs/en/enterprise-edition/content-collections/_graphics/search-and-investigate/build-modify-4.png
  docs/en/enterprise-edition/content-collections/_graphics/search-and-investigate/build-modify.png
  docs/en/enterprise-edition/content-collections/_graphics/search-and-investigate/custom-search-1.png
  docs/en/enterprise-edition/content-collections/_graphics/search-and-investigate/custom-search-save-1.png
  docs/en/enterprise-edition/content-collections/_graphics/search-and-investigate/explore-data-3.png
  docs/en/enterprise-edition/content-collections/_graphics/search-and-investigate/investigate-overview-1.png
  docs/en/enterprise-edition/content-collections/_graphics/search-and-investigate/investigate-overview-2.png
  docs/en/enterprise-edition/content-collections/_graphics/search-and-investigate/query-library-1.png
  docs/en/enterprise-edition/content-collections/_graphics/search-and-investigate/save-policy-1.png
  docs/en/enterprise-edition/content-collections/_graphics/search-and-investigate/save-policy-2.png
  docs/en/enterprise-edition/content-collections/_graphics/search-and-investigate/simple-search-graph-1.png
  docs/en/enterprise-edition/content-collections/_graphics/search-and-investigate/simple-search-table-1.png
  docs/en/enterprise-edition/content-collections/search-and-investigate/build-modify-queries.adoc
  docs/en/enterprise-edition/content-collections/search-and-investigate/explore-data.adoc
  docs/en/enterprise-edition/content-collections/search-and-investigate/launch-your-query.adoc
  docs/en/enterprise-edition/content-collections/search-and-investigate/query-library.adoc
Labels: documentation, ready-to-be-merged

#177 [Newton Update 2 Build 31-02-137]: PCCE RN
  docs/en/compute-edition/31/rn/book.yml
  docs/en/compute-edition/31/rn/book_point_release.yml
  docs/en/compute-edition/31/rn/release-information/release-notes-31-02-update2-build-31-02-137.adoc
Labels: documentation, do-not-merge

#190 Azure updates
  docs/en/classic/compute-admin-guide/tools/twistcli-scan-iac.adoc
  docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-your-azure-account/connect-azure-account.adoc
  docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-your-azure-account/connect-azure-active-directory.adoc
Labels: documentation

#194 Fix Bitbucket name and webhook image
  docs/en/classic/appsec-admin-guide/_graphics/bitbucket-6.png
  docs/en/classic/appsec-admin-guide/get-started/connect-your-repositories/code-repositories/add-bitbucket.adoc
  docs/en/enterprise-edition/content-collections/application-security/get-started/connect-code-and-build-providers/code-repositories/add-bitbucket.adoc
Labels: documentation, ready-to-be-merged

#195 [Compute AG]Update alert frequencies.
  docs/en/classic/compute-admin-guide/_graphics/frag_configure_alerts.png
  docs/en/classic/compute-admin-guide/alerts/frag-config-rate.adoc
  docs/en/compute-edition/31/admin-guide/_graphics/frag_configure_alerts.png
  docs/en/compute-edition/31/admin-guide/alerts/frag-config-rate.adoc
Labels: bug, documentation

#199 [Compute AG]Fix permissions table for Classic
  docs/en/classic/compute-admin-guide/configure/permissions.adoc
  docs/en/compute-edition/30/admin-guide/configure/permissions.adoc
  docs/en/compute-edition/31/admin-guide/configure/permissions.adoc
Labels: bug, documentation

#180 [Runtime Security]: Update GKE Autopilot Defender command
  docs/en/compute-edition/31/admin-guide/install/deploy-defender/orchestrator/install-gke-autopilot.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/install/deploy-defender/kubernetes/gke-autopilot.adoc
Labels: documentation
