Repository hlxsites/prisma-cloud-docs, pull requests merged in 2024-01, with the labels that each got.

#294 PCSUP-18383 update
  docs/en/classic/cspm-admin-guide/prisma-cloud-iam-security/cloud-identity-inventory.adoc
  docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-your-azure-account/connect-azure-account.adoc
  docs/en/enterprise-edition/content-collections/get-started/adoption-advisor.adoc
Labels: documentation, do-not-merge

#304 [Runtime Security PCCE] O'Neal Update 1 Release Notes
  docs/en/compute-edition/32/rn/book.yml
  docs/en/compute-edition/32/rn/book_point_release.yml
  docs/en/compute-edition/32/rn/release-information/release-notes-32-00.adoc
  docs/en/compute-edition/32/rn/release-information/release-notes-32-01.adoc
Labels: documentation, O'Neal Update 1

#302 [Runtime Security PCEE] O'Neal Update 1 Release Notes
  docs/en/enterprise-edition/rn/book.yml
  docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
  docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-compute-release-information/features-introduced-in-compute-january-2024.adoc
Labels: documentation, O'Neal Update 1

#276 [Darwin - Search & Investigate] RQL updates
  docs/en/classic/rql-reference/rql-reference/config-query/config-query-attributes.adoc
  docs/en/enterprise-edition/content-collections/alerts/view-respond-to-prisma-cloud-alerts.adoc
  docs/en/enterprise-edition/content-collections/book.yml
  docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/connect-cloud-accounts.adoc
  docs/en/enterprise-edition/content-collections/search-and-investigate/asset-config-queries/asset-config-query-attributes.adoc
  docs/en/enterprise-edition/content-collections/search-and-investigate/collection-search-and-investigate.yml
  docs/en/enterprise-edition/content-collections/search-and-investigate/network-queries/network-config-query-attributes.adoc
  docs/en/enterprise-edition/content-collections/search-and-investigate/network-queries/network-config-query-examples.adoc
  docs/en/enterprise-edition/content-collections/search-and-investigate/network-queries/network-flow-query-attributes.adoc
  docs/en/enterprise-edition/content-collections/search-and-investigate/network-queries/network-flow-query-examples.adoc
  docs/en/enterprise-edition/content-collections/search-and-investigate/permissions-queries/permissions-query-conditions.adoc
  docs/en/enterprise-edition/content-collections/search-and-investigate/rql-examples.adoc
  docs/en/enterprise-edition/content-collections/search-and-investigate/rql-faqs.adoc
  docs/en/enterprise-edition/content-collections/search-and-investigate/rql-operators.adoc
  docs/en/enterprise-edition/content-collections/search-and-investigate/search-and-investigate.adoc
Labels: documentation, do-not-merge

#323 PCDTUS-78
  docs/en/classic/cspm-admin-guide/prisma-cloud-data-security/what-is-included-with-prisma-cloud-data-security.adoc
  docs/en/enterprise-edition/content-collections/administration/configure-data-security/what-is-included-with-prisma-cloud-data-security.adoc
  docs/en/enterprise-edition/content-collections/search-and-investigate/application-asset-queries/application-asset-build-explore.adoc
  docs/en/enterprise-edition/content-collections/search-and-investigate/asset-queries/asset-queries.adoc
Labels: documentation

#314 [Release Notes] 24.1.1 - Jan 11 publish
  docs/en/classic/cspm-admin-guide/manage-prisma-cloud-alerts/create-an-alert-rule.adoc
  docs/en/compute-edition/32/rn/release-information/release-notes-32-01.adoc
  docs/en/enterprise-edition/content-collections/_graphics/administration/add-email-notification-template-1.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/add-email-notification-template-2.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/add-jira-notification-template-1.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/add-jira-notification-template-2.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/add-jira-notification-template-3.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/alerts-alert-rules-set-alert-notification.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/cdem-subscription-enable.png
  docs/en/enterprise-edition/content-collections/administration/configure-external-integrations-on-prisma-cloud/add-notification-template.adoc
  docs/en/enterprise-edition/content-collections/administration/configure-external-integrations-on-prisma-cloud/integrate-prisma-cloud-with-jira.adoc
  docs/en/enterprise-edition/content-collections/administration/subscribe-to-cdem.adoc
  docs/en/enterprise-edition/rn/book.yml
  docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
  docs/en/enterprise-edition/rn/limited-ga-features-prisma-cloud/limited-ga-features-prisma-cloud.adoc
  docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
  docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-source.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-compute-release-information/prisma-cloud-compute-release-information.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-cspm-release-information/features-introduced-in-april-2023.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2023/features-introduced-in-december-2023.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-2024.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-january-2024.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/prisma-cloud-release-info.adoc
Labels: documentation

#290 Resorted Sast Policies jb
  docs/en/enterprise-edition/policy-reference/sast-policies/java-policies/sast-java-policy-index.adoc
  docs/en/enterprise-edition/policy-reference/sast-policies/javascript-policies/sast-javascript-policy-index.adoc
  docs/en/enterprise-edition/policy-reference/sast-policies/python-policies/sast-python-policy-index.adoc
Labels: do-not-merge

#311 Revised Secrets documentation and added CLI flags
  docs/en/enterprise-edition/content-collections/_graphics/application-security/secrets-advanced-settings.png
  docs/en/enterprise-edition/content-collections/application-security/risk-management/monitor-and-manage-code-build/secrets-scanning.adoc
Labels: ready-to-be-merged

#296 [APP-SEC] Adding Terraform Module Scanning to Monitor and Manage Code Build
  docs/en/enterprise-edition/content-collections/_graphics/application-security/tf-module-scan.png
  docs/en/enterprise-edition/content-collections/application-security/collection-application-security.yml
  docs/en/enterprise-edition/content-collections/application-security/risk-management/monitor-and-manage-code-build/terraform-module-scan.adoc
  docs/en/enterprise-edition/content-collections/book.yml
Labels: documentation, ready-to-be-merged

#252 AppSec CI/CD Policies
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/azure-repo-cicd-pipeline-policies/azure-repo-dependency-confusion.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/azure-repo-cicd-pipeline-policies/azure-repo-deprecated-package-in-npm.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/azure-repo-cicd-pipeline-policies/azure-repo-missing-npmrc-file.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/azure-repo-cicd-pipeline-policies/azure-repo-python-typosquat-detected.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/azure-repo-cicd-pipeline-policies/azure-repo-secret-registry-url-npmrcfile.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/azure-repo-cicd-pipeline-policies/azure-repo-unencrypted-channel-download-dependecies-proxy.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/azure-repo-cicd-pipeline-policies/azure-repo-unencrypted-channel-download-dependecies-registry.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/azure-repo-cicd-pipeline-policies/azure-repo-unpinned-container-image.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/azure-repo-cicd-pipeline-policies/azure-repos-secret-proxy-url-npmrcfile.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/bitbucket-cicd-pipeline-policies/bb-deprecated-pckg-npm-project.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/bitbucket-cicd-pipeline-policies/bb-missing-npmrc-file.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/bitbucket-cicd-pipeline-policies/bb-possible-python-typosquat-repo.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/bitbucket-cicd-pipeline-policies/bb-potential-dependency-confusion.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/bitbucket-cicd-pipeline-policies/bb-private-repo-made-public.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/bitbucket-cicd-pipeline-policies/bb-secrets-exposed-proxyurl-npmrc.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/bitbucket-cicd-pipeline-policies/bb-secrets-exposed-registryurl-npmrc.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/bitbucket-cicd-pipeline-policies/bb-unencrypted-channel-download-dependencies-proxy.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/bitbucket-cicd-pipeline-policies/bb-unencrypted-channel-download-dependencies-registry.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/circleci-cicd-pipeline-policies/circleci-pipeline-unpinned-image.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/github-cicd-pipeline-policies/gh-deprecated-pckg-npm-project.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/github-cicd-pipeline-policies/gh-missing-npmrc-file.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/github-cicd-pipeline-policies/gh-possible-python-typosquat-repo.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/github-cicd-pipeline-policies/gh-potential-dependency-confusion.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/github-cicd-pipeline-policies/gh-secrets-exposed-proxyurl-npmrc.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/github-cicd-pipeline-policies/gh-secrets-exposed-registryurl-npmrc.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/github-cicd-pipeline-policies/gh-unencrypted-channel-download-dependencies-proxy.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/github-cicd-pipeline-policies/gh-unencrypted-channel-download-dependencies-registry.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/github-cicd-pipeline-policies/gha-unrotated-org-secrets.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/github-cicd-pipeline-policies/gha-unrotated-repo-secrets.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/gitlab-cicd-pipeline-policies/gl-deprecated-pckg-npm-project.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/gitlab-cicd-pipeline-policies/gl-missing-npmrc-file.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/gitlab-cicd-pipeline-policies/gl-possible-python-typosquat-repo.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/gitlab-cicd-pipeline-policies/gl-potential-dependency-confusion.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/gitlab-cicd-pipeline-policies/gl-repos-secrets-in-pipeline-logs.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/gitlab-cicd-pipeline-policies/gl-secrets-exposed-proxyurl-npmrc.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/gitlab-cicd-pipeline-policies/gl-secrets-exposed-registryurl-npmrc.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/gitlab-cicd-pipeline-policies/gl-unencrypted-channel-download-dependencies-proxy.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/gitlab-cicd-pipeline-policies/gl-unencrypted-channel-download-dependencies-registry.adoc
Labels: documentation, ready-to-be-merged

#327 Uncommented SAST policies in yml book
  docs/en/enterprise-edition/policy-reference/book.yml
Labels: documentation

#334 [Runtime Security PCEE] O'Neal Update 2 Look Ahead
  docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
Labels: documentation, O'Neal Update 2

#325 RLP-126951
  docs/en/classic/cspm-admin-guide/connect-your-cloud-platform-to-prisma-cloud/onboard-your-azure-account/connect-azure-account.adoc
  docs/en/classic/cspm-admin-guide/prisma-cloud-iam-security/remediate-alerts-for-iam-security.adoc
  docs/en/enterprise-edition/content-collections/_graphics/administration/iam-security-alert-violating-policy.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/iam-security-policy-type.png
  docs/en/enterprise-edition/content-collections/administration/configure-iam-security/remediate-alerts-for-iam-security.adoc
  docs/en/enterprise-edition/content-collections/governance/create-a-policy.adoc
Labels: bug, documentation, do-not-merge

#343 Clean up based on slack request from Stephanie
  docs/en/enterprise-edition/content-collections/_graphics/administration/add-servicenow-notification-template-1.png
  docs/en/enterprise-edition/content-collections/administration/configure-external-integrations-on-prisma-cloud/add-notification-template.adoc
  docs/en/enterprise-edition/content-collections/administration/configure-external-integrations-on-prisma-cloud/integrate-prisma-cloud-with-jira.adoc
  docs/en/enterprise-edition/content-collections/administration/configure-external-integrations-on-prisma-cloud/integrate-prisma-cloud-with-servicenow.adoc
Labels: documentation

#356 oneal1 fixes
  docs/en/enterprise-edition/content-collections/administration/prisma-cloud-licenses.adoc
  docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-aws/update-onboarded-aws-accnt-to-org.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/runtime-security-components/licensing/licensing.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/runtime-security.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/vulnerability-management/vulnerability-explorer.adoc
Labels: bug, documentation, do-not-merge

#353 [Runtime Security PCEE] O'Neal Update 2 Release Notes
  docs/en/enterprise-edition/rn/book.yml
  docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
  docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-compute-release-information/features-introduced-in-compute-february-2024.adoc
Labels: do-not-merge, O'Neal Update 2

#354 [Runtime Security PCCE] O'Neal Update 2 Release Notes
  docs/en/compute-edition/32/rn/book.yml
  docs/en/compute-edition/32/rn/book_point_release.yml
  docs/en/compute-edition/32/rn/release-information/release-notes-32-02.adoc
Labels: do-not-merge, O'Neal Update 2
