Repository hlxsites/prisma-cloud-docs, pull requests merged in 2024-02, with the labels that each got.

#371 Doc-rn-updates-RLP-127621
  docs/en/classic/cspm-admin-guide/manage-prisma-cloud-administrators/add-a-resource-list-on-prisma-cloud.adoc
  docs/en/classic/cspm-admin-guide/prisma-cloud-dashboards/asset-inventory.adoc
  docs/en/enterprise-edition/content-collections/administration/add-a-resource-list-on-prisma-cloud.adoc
  docs/en/enterprise-edition/content-collections/cloud-and-software-inventory/asset-inventory.adoc
  docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
Labels: documentation, do-not-merge

#370 1.2 rn update
  docs/.vscode/settings.json
  docs/en/enterprise-edition/content-collections/dashboards/create-and-manage-dashboards.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-january-2024.adoc
Labels: documentation, do-not-merge

#368 [Runtime Security]Fix permissions page navigation
  docs/en/classic/compute-admin-guide/configure/permissions.adoc
  docs/en/compute-edition/32/admin-guide/configure/permissions.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/configure/permissions.adoc
Labels: documentation, O'Neal Update 2

#362 [Runtime Security]Clarify missing Istio containers
  docs/en/compute-edition/32/admin-guide/install/system-requirements.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/install/system-requirements.adoc
Labels: bug, documentation, O'Neal Update 1

#377 [Runtime Security]Fix image rendering in fragments
  docs/en/classic/compute-admin-guide/agentless-scanning/onboard-accounts/frag-start-agentless-scan.adoc
  docs/en/classic/compute-admin-guide/alerts/frag-config-triggers.adoc
  docs/en/classic/compute-admin-guide/alerts/frag-send-alerts.adoc
  docs/en/classic/compute-admin-guide/install/fragments/install-defender-twistcli-export-oc-3-11.adoc
  docs/en/classic/compute-admin-guide/waas/deploy-waas/fragments/add-app-policy.adoc
  docs/en/classic/compute-admin-guide/waas/deploy-waas/fragments/create-waas-rule.adoc
  docs/en/classic/compute-admin-guide/waas/deploy-waas/fragments/defender-deployment-failed-troubleshoot.adoc
  docs/en/compute-edition/22-12/admin-guide/agentless-scanning/onboard-accounts/frag-start-agentless-scan.adoc
  docs/en/compute-edition/22-12/admin-guide/alerts/frag-config-rate.adoc
  docs/en/compute-edition/22-12/admin-guide/alerts/frag-config-triggers.adoc
  docs/en/compute-edition/22-12/admin-guide/alerts/frag-send-alerts.adoc
  docs/en/compute-edition/22-12/admin-guide/waas/deploy-waas/fragments/add-app-policy.adoc
  docs/en/compute-edition/22-12/admin-guide/waas/deploy-waas/fragments/create-waas-rule.adoc
  docs/en/compute-edition/22-12/admin-guide/waas/deploy-waas/fragments/defender-deployment-failed-troubleshoot.adoc
  docs/en/compute-edition/30/admin-guide/agentless-scanning/onboard-accounts/frag-start-agentless-scan.adoc
  docs/en/compute-edition/30/admin-guide/alerts/frag-config-rate.adoc
  docs/en/compute-edition/30/admin-guide/alerts/frag-config-triggers.adoc
  docs/en/compute-edition/30/admin-guide/alerts/frag-send-alerts.adoc
  docs/en/compute-edition/30/admin-guide/install/fragments/install-defender-twistcli-export-oc-3-11.adoc
  docs/en/compute-edition/30/admin-guide/waas/deploy-waas/fragments/add-app-policy.adoc
  docs/en/compute-edition/30/admin-guide/waas/deploy-waas/fragments/create-waas-rule.adoc
  docs/en/compute-edition/30/admin-guide/waas/deploy-waas/fragments/defender-deployment-failed-troubleshoot.adoc
  docs/en/compute-edition/31/admin-guide/agentless-scanning/onboard-accounts/frag-start-agentless-scan.adoc
  docs/en/compute-edition/31/admin-guide/alerts/frag-config-triggers.adoc
  docs/en/compute-edition/31/admin-guide/alerts/frag-send-alerts.adoc
  docs/en/compute-edition/31/admin-guide/install/fragments/install-defender-twistcli-export-oc-3-11.adoc
  docs/en/compute-edition/31/admin-guide/waas/deploy-waas/fragments/add-app-policy.adoc
  docs/en/compute-edition/31/admin-guide/waas/deploy-waas/fragments/create-waas-rule.adoc
  docs/en/compute-edition/32/admin-guide/agentless-scanning/onboard-accounts/frag-start-agentless-scan.adoc
  docs/en/compute-edition/32/admin-guide/alerts/frag-config-triggers.adoc
  docs/en/compute-edition/32/admin-guide/alerts/frag-send-alerts.adoc
  docs/en/compute-edition/32/admin-guide/install/fragments/install-defender-twistcli-export-oc-3-11.adoc
  docs/en/compute-edition/32/admin-guide/waas/deploy-waas/fragments/add-app-policy.adoc
  docs/en/compute-edition/32/admin-guide/waas/deploy-waas/fragments/create-waas-rule.adoc
  docs/en/compute-edition/32/admin-guide/waas/deploy-waas/fragments/defender-deployment-failed-troubleshoot.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/agentless-scanning/configure-accounts/frag-start-agentless-scan.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/alerts/frag-config-rate.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/alerts/frag-config-triggers.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/alerts/frag-send-alerts.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/install/fragments/install-defender-twistcli-export-oc-3-11.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/waas/deploy-waas/fragments/add-app-policy.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/waas/deploy-waas/fragments/create-waas-rule.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/waas/deploy-waas/fragments/defender-deployment-failed-troubleshoot.adoc
Labels: bug, documentation

#376 OIDC sso topic updates
  docs/en/enterprise-edition/content-collections/_graphics/administration/oidc-sso.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/oidc.png
  docs/en/enterprise-edition/content-collections/administration/setup-sso-integration-on-prisma-cloud/get-started-with-oidc-sso/get-started-with-oidc-sso.adoc
  docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-aws/update-onboarded-aws-accnt-to-org.adoc
Labels: bug, documentation

#393 [CSPM Collections] - Updates to CDEM and connect collections.
  docs/en/classic/cspm-admin-guide/connect-your-cloud-platform-to-prisma-cloud/cloud-service-provider-regions-on-prisma-cloud.adoc
  docs/en/classic/cspm-admin-guide/connect-your-cloud-platform-to-prisma-cloud/onboard-gcp/prerequisites-to-onboard-gcp.adoc
  docs/en/enterprise-edition/content-collections/administration/subscribe-to-cdem.adoc
  docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/cloud-service-provider-regions-on-prisma-cloud.adoc
  docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-gcp/prerequisites-to-onboard-gcp.adoc
Labels: documentation

#381 [Runtime Security][PCEE] Look Ahead - O'Neal Update 3
  docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
Labels: do-not-merge, O'Neal Update 3

#408 fixed broken links in get-started and missing .adoc ext in book
  docs/en/enterprise-edition/policy-reference/book.yml
  docs/en/enterprise-edition/policy-reference/get-started-code-sec-policies/get-started-code-sec-policies.adoc
Labels: documentation

#417 {Draft] Revised as plans for migration to AWS have been dropped
  docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
Labels: do-not-merge

#322 OIDC JIT
  docs/en/enterprise-edition/content-collections/_graphics/administration/oic-jit-okta-api.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/oidc-jit-azure-api.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/oidc-jit-azure-token.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/oidc-jit-okta-token.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/oidc-jit.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/oidc-okta-group-claim.png
  docs/en/enterprise-edition/content-collections/administration/setup-sso-integration-on-prisma-cloud/get-started-with-oidc-sso/get-started-with-oidc-jit.adoc
  docs/en/enterprise-edition/content-collections/book.yml
  docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-february-2024.adoc
Labels: documentation, do-not-merge

#427 [CSPM Collections] - 24.2.2 updates by AN
  docs/en/classic/cspm-admin-guide/_graphics/add-snow-auth-summary.png
  docs/en/classic/cspm-admin-guide/_graphics/add-snow-auth-test.png
  docs/en/classic/cspm-admin-guide/_graphics/edit-snow-integration-1.png
  docs/en/classic/cspm-admin-guide/_graphics/edit-snow-integration-2.png
  docs/en/classic/cspm-admin-guide/_graphics/edit-snow-integration-3.png
  docs/en/classic/cspm-admin-guide/_graphics/generate-oauth-token-1.png
  docs/en/classic/cspm-admin-guide/_graphics/manage-snow-integration.png
  docs/en/classic/cspm-admin-guide/_graphics/setup-snow-1.png
  docs/en/classic/cspm-admin-guide/_graphics/setup-snow-2.png
  docs/en/classic/cspm-admin-guide/_graphics/setup-snow-3.png
  docs/en/classic/cspm-admin-guide/_graphics/snow-basic-auth-1.png
  docs/en/classic/cspm-admin-guide/_graphics/snow-oauth-1.png
  docs/en/classic/cspm-admin-guide/configure-external-integrations-on-prisma-cloud/integrate-prisma-cloud-with-servicenow.adoc
  docs/en/classic/cspm-admin-guide/get-started-with-prisma-cloud/enable-access-prisma-cloud-console.adoc
  docs/en/enterprise-edition/content-collections/_graphics/administration/add-snow-auth-summary.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/add-snow-auth-test.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/edit-snow-integration-1.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/edit-snow-integration-2.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/edit-snow-integration-3.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/generate-oauth-token-1.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/manage-snow-integration.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/setup-snow-1.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/setup-snow-2.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/setup-snow-3.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/snow-basic-auth-1.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/snow-oauth-1.png
  docs/en/enterprise-edition/content-collections/administration/configure-external-integrations-on-prisma-cloud/integrate-prisma-cloud-with-servicenow.adoc
  docs/en/enterprise-edition/content-collections/get-started/console-prerequisites.adoc
Labels: documentation

#436 [Runtime Security][CWP-55524] Update scanning modes to include Azure
  docs/en/classic/compute-admin-guide/agentless-scanning/agentless-scanning-modes.adoc
  docs/en/compute-edition/32/admin-guide/agentless-scanning/agentless-scanning-modes.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/agentless-scanning/agentless-scanning-modes.adoc
Labels: documentation, O'Neal Update 3

#445 cns updates
  docs/en/classic/cspm-admin-guide/get-started-with-prisma-cloud/enable-access-prisma-cloud-console.adoc
  docs/en/enterprise-edition/rn/limited-ga-features-prisma-cloud/limited-ga-features-prisma-cloud.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-february-2024.adoc
Labels: do-not-merge

#339 [AppSec Policy Ref] Fix errors in Policy Reference Guide
  docs/en/enterprise-edition/policy-reference/aws-policies/aws-networking-policies/bc-aws-networking-66.adoc
  docs/en/enterprise-edition/policy-reference/azure-policies/azure-general-policies/azure-general-policies.adoc
  docs/en/enterprise-edition/policy-reference/azure-policies/azure-networking-policies/azure-networking-policies.adoc
  docs/en/enterprise-edition/policy-reference/book.yml
  docs/en/enterprise-edition/policy-reference/build-integrity-policies/github-policies/ensure-repository-is-private.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/azure-repo-cicd-pipeline-policies/azure-repo-cicd-pipeline-policies.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/azure-repo-cicd-pipeline-policies/azure-repo-pr-review-notrequired-merge.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/azure-repo-cicd-pipeline-policies/azure-repo-requestors-self-approve-pr-defaultbranch.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/circleci-cicd-pipeline-policies/circleci-vulnerable-cmnd-injection.adoc
  docs/en/enterprise-edition/policy-reference/ci-cd-pipeline-policies/github-cicd-pipeline-policies/gh-code-owners-review-not-required-tomerge.adoc
  docs/en/enterprise-edition/policy-reference/docker-policies/docker-policy-index/docker-policy-index.adoc
  docs/en/enterprise-edition/policy-reference/sast-policies/java-policies/java-policies.adoc
  docs/en/enterprise-edition/policy-reference/sast-policies/javascript-policies/javascript-policies.adoc
  docs/en/enterprise-edition/policy-reference/sast-policies/python-policies/python-policies.adoc
Labels: do-not-merge

#307 [Runtime Security AG] CWP-39604
  docs/en/classic/compute-admin-guide/book.yml
  docs/en/classic/compute-admin-guide/runtime-defense/incident-types/brute-force.adoc
  docs/en/classic/compute-admin-guide/runtime-defense/incident-types/incident-types.adoc
  docs/en/compute-edition/22-12/admin-guide/book.yml
  docs/en/compute-edition/22-12/admin-guide/runtime-defense/incident-types/brute-force.adoc
  docs/en/compute-edition/30/admin-guide/book.yml
  docs/en/compute-edition/30/admin-guide/runtime-defense/incident-types/brute-force.adoc
  docs/en/compute-edition/30/admin-guide/runtime-defense/incident-types/incident-types.adoc
  docs/en/compute-edition/31/admin-guide/book.yml
  docs/en/compute-edition/31/admin-guide/runtime-defense/incident-types/brute-force.adoc
  docs/en/compute-edition/31/admin-guide/runtime-defense/incident-types/incident-types.adoc
  docs/en/compute-edition/32/admin-guide/book.yml
  docs/en/compute-edition/32/admin-guide/runtime-defense/incident-types/brute-force.adoc
  docs/en/compute-edition/32/admin-guide/runtime-defense/incident-types/incident-types.adoc
  docs/en/enterprise-edition/content-collections/book.yml
  docs/en/enterprise-edition/content-collections/runtime-security/collection-runtime-security.yml
  docs/en/enterprise-edition/content-collections/runtime-security/runtime-defense/incident-types/brute-force.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/runtime-defense/incident-types/incident-types.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/runtime-security-collection.yml
Labels: documentation, ready-to-be-merged, O'Neal Update 3

#431 [Runtime Security] Move list of AWS permissions needed
  docs/en/classic/compute-admin-guide/configure/permissions.adoc
  docs/en/compute-edition/32/admin-guide/configure/permissions.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/configure/permissions.adoc
Labels: documentation, ready-to-be-merged, O'Neal Update 3

#421 [Runtime Security-RN] O'Neal Update 3 PCCE
  docs/en/compute-edition/32/rn/book_point_release.yml
  docs/en/compute-edition/32/rn/release-information/release-notes-32-03.adoc
Labels: ready-to-be-merged, O'Neal Update 3

#411 [Runtime Security RN] O'Neal Update 3 - PCEE
  docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
  docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-compute-release-information/features-introduced-in-compute-february-2024.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-compute-release-information/features-introduced-in-compute-january-2024.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-compute-release-information/prisma-cloud-compute-release-information.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-february-2024.adoc
Labels: ready-to-be-merged, O'Neal Update 3
