Repository hlxsites/prisma-cloud-docs, pull requests merged in 2024-04, with the labels that each got.

#499 [Alerts][pcsup-21253]Add maximum value accepted for alert triggering
  docs/en/enterprise-edition/content-collections/alerts/create-an-alert-rule-cloud-infrastructure.adoc
Labels: bug, documentation, O'Neal Update 4

#558 [CC - Administration] - Updates to Configure External Integrations on Prisma Cloud 24.4.1
  docs/en/enterprise-edition/content-collections/_graphics/administration/amazon-s3-int-1.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/amazon-s3-int-2.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/amazon-s3-int-3.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/amazon-s3-int-4.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/guardduty-audit-trail.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/guardduty-host-findings.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/guardduty-network-query.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/inspector-audit-trail-query.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/inspector-findings-query.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/inspector-network-query.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/pagerduty-integration-on-prisma-cloud.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/slack-add-integration-in-pc-1.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/slack-add-integration-in-pc-2.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/slack-add-integration-in-pc-3.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/splunk-add-integration-in-pc-3.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/tenable-audit-trail.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/tenable-findings-trail.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/tenable-host-findings-view.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/tenable-hostfinding-config-query.png
  docs/en/enterprise-edition/content-collections/administration/configure-external-integrations-on-prisma-cloud/integrate-prisma-cloud-with-amazon-guardduty.adoc
  docs/en/enterprise-edition/content-collections/administration/configure-external-integrations-on-prisma-cloud/integrate-prisma-cloud-with-amazon-s3.adoc
  docs/en/enterprise-edition/content-collections/administration/configure-external-integrations-on-prisma-cloud/integrate-prisma-cloud-with-aws-inspector.adoc
  docs/en/enterprise-edition/content-collections/administration/configure-external-integrations-on-prisma-cloud/integrate-prisma-cloud-with-pagerduty.adoc
  docs/en/enterprise-edition/content-collections/administration/configure-external-integrations-on-prisma-cloud/integrate-prisma-cloud-with-qualys.adoc
  docs/en/enterprise-edition/content-collections/administration/configure-external-integrations-on-prisma-cloud/integrate-prisma-cloud-with-slack.adoc
  docs/en/enterprise-edition/content-collections/administration/configure-external-integrations-on-prisma-cloud/integrate-prisma-cloud-with-splunk.adoc
  docs/en/enterprise-edition/content-collections/administration/configure-external-integrations-on-prisma-cloud/integrate-prisma-cloud-with-tenable.adoc
Labels: documentation

#579 [Administration] & [Get Started] - Content Collections for 24.4.2 by AN
  docs/en/classic/cspm-admin-guide/get-started-with-prisma-cloud/enable-access-prisma-cloud-console.adoc
  docs/en/enterprise-edition/content-collections/_graphics/administration/cortex-xsoar-int-1.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/cortex-xsoar-int-2.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/cortex-xsoar-int-3.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/cortex-xsoar-int-4.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/cortex-xsoar-int-for-6-ver.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/demisto-api-end-mapping.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/demisto-integration-path.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/demisto-integration-prisma-cloud-incident-playbooks.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/demisto-integration-pull-based-prisma-cloud.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/demisto-optional-add-integration.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/demisto-pc-v2-instance.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/demisto-prisma-classifier.png
  docs/en/enterprise-edition/content-collections/administration/configure-external-integrations-on-prisma-cloud/integrate-prisma-cloud-with-cortex-xsoar.adoc
  docs/en/enterprise-edition/content-collections/alerts/send-prisma-cloud-alert-notifications-to-third-party-tools.adoc
  docs/en/enterprise-edition/content-collections/application-security/application-security.adoc
  docs/en/enterprise-edition/content-collections/get-started/access-prisma-cloud.adoc
  docs/en/enterprise-edition/content-collections/get-started/console-prerequisites.adoc
Labels: documentation, ready-to-be-merged

#570 4-2-RN
  docs/en/enterprise-edition/rn/_graphics/share-views.gif
  docs/en/enterprise-edition/rn/_graphics/xsoar-integration.png
  docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-april-2024.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-march-2024.adoc
Labels: do-not-merge

#448 [Runtime Security] CWP-56018
  docs/en/classic/compute-admin-guide/alerts/webhook.adoc
Labels: O'Neal Update 3

#572 [Runtime Security] LA O'Neal Update 5
  docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
Labels: do-not-merge, O'Neal Update 5

#437 [Runtime Security][CWP-54524]Add result column to the compliance expl…
  docs/en/classic/compute-admin-guide/compliance/compliance-explorer.adoc
  docs/en/compute-edition/32/admin-guide/compliance/compliance-explorer.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/compliance/visibility/compliance-explorer.adoc
Labels: documentation, O'Neal Update 3

#179 [CWP-36043 - Deprecate repo scan with twistcli]
  docs/en/enterprise-edition/content-collections/book.yml
  docs/en/enterprise-edition/content-collections/runtime-security/collection-runtime-security.yml
  docs/en/enterprise-edition/content-collections/runtime-security/continuous-integration/code-repo-scanning.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/runtime-security-collection.yml
  docs/en/enterprise-edition/content-collections/runtime-security/vulnerability-management/scan-code-repository.adoc
Labels: O'Neal Update 4

#525 [Runtime Security] [AG] CWP-36043 Patch
  docs/en/classic/compute-admin-guide/continuous-integration/code-repo-scanning.adoc
  docs/en/classic/compute-admin-guide/vulnerability-management/code-repo-scanning.adoc
  docs/en/compute-edition/32/admin-guide/continuous-integration/code-repo-scanning.adoc
  docs/en/compute-edition/32/admin-guide/vulnerability-management/code-repo-scanning.adoc
Labels: O'Neal Update 4

#577 [Runtime Security] AG- CWP-56983
  docs/en/classic/compute-admin-guide/upgrade/upgrade-defender-single-container.adoc
  docs/en/compute-edition/32/admin-guide/upgrade/frag-upgrade-defender-single-container.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/upgrade/frag-upgrade-defender-single-container.adoc
Labels: O'Neal Update 4

#526 [Runtime Security AG] CWP-54807
  docs/en/classic/compute-admin-guide/alerts/jira.adoc
  docs/en/compute-edition/32/admin-guide/alerts/jira.adoc
Labels: O'Neal Update 4

#599 [Runtime Security] Patch for CWP-56983
  docs/en/compute-edition/30/admin-guide/upgrade/upgrade-defender-single-container.adoc
  docs/en/compute-edition/31/admin-guide/upgrade/upgrade-defender-single-container.adoc
  docs/en/compute-edition/32/admin-guide/upgrade/upgrade-defender-single-container.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/collection-runtime-security.yml
  docs/en/enterprise-edition/content-collections/runtime-security/upgrade/upgrade-defender-single-container.adoc
Labels: O'Neal Update 4
