Repository hlxsites/prisma-cloud-docs, pull requests merged in 2024-06, with the labels that each got.

#684 [Runtime Security] AG CWP-57083
  docs/en/compute-edition/32/admin-guide/vulnerability-management/vuln-explorer.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/vulnerability-management/vulnerability-explorer.adoc
Labels: O'Neal Update 6 (Pascal)

#668 [Runtime Security] CWP-55880 (59034)
  docs/en/compute-edition/32/admin-guide/audit/logging.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/audit/logging.adoc
Labels: O'Neal Update 6 (Pascal)

#665 [Runtime Security] CWP- 54508
  docs/en/compute-edition/32/admin-guide/waas/deploy-waas/deployment-vpc-mirroring.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/waas/deploy-waas/vpc-mirroring.adoc
Labels: O'Neal Update 6 (Pascal)

#667 [Runtime Security] CWP-55308
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-may-2024.adoc
Labels: O'Neal Update 6 (Pascal)

#709 [CSPM RN] 24.6.2 Release Notes
  docs/en/classic/cspm-admin-guide/connect-your-cloud-platform-to-prisma-cloud/onboard-gcp/prerequisites-to-onboard-gcp.adoc
  docs/en/enterprise-edition/content-collections/administration/subscribe-to-cdem.adoc
  docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-gcp/prerequisites-to-onboard-gcp.adoc
  docs/en/enterprise-edition/rn/_graphics/c2c-update-20.png
  docs/en/enterprise-edition/rn/_graphics/data-security-compliance-1.png
  docs/en/enterprise-edition/rn/_graphics/data-security-compliance-2.png
  docs/en/enterprise-edition/rn/_graphics/uve-rbac.png
  docs/en/enterprise-edition/rn/limited-ga-features-prisma-cloud/limited-ga-features-prisma-cloud.adoc
  docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-june-2024.adoc
Labels: documentation

#711 [Runtime Security] Quick Fix for RN
  docs/en/compute-edition/32/rn/release-information/release-notes-32-05.adoc
Labels: O'Neal Update 6 (Pascal)

#712 LGA Update
  docs/en/enterprise-edition/rn/limited-ga-features-prisma-cloud/limited-ga-features-prisma-cloud.adoc
Labels: do-not-merge

#710 PCSUP-22899 Doc Updates
  docs/en/enterprise-edition/content-collections/_graphics/search-and-investigate/json-rule-1.png
  docs/en/enterprise-edition/content-collections/search-and-investigate/asset-config-queries/asset-config-query-attributes.adoc
  docs/en/enterprise-edition/content-collections/search-and-investigate/build-modify-queries.adoc
Labels: do-not-merge

#724 Doc enhancement for PCSUP-23439 (RLP-143685)
  docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-gcp/onboard-gcp-workspace.adoc
Labels: documentation
