Repository hlxsites/prisma-cloud-docs, pull requests merged in 2024-03, with the labels that each got.

#438 [Runtime Security][CWP-39151]Add details to use the DNS to deploy the…
  docs/en/compute-edition/32/admin-guide/install/deploy-console/console-on-amazon-ecs.adoc
Labels: documentation, O'Neal Update 3

#462 azure-perms+copy-fix
  docs/en/classic/compute-admin-guide/configure/permissions.adoc
  docs/en/classic/cspm-admin-guide/prisma-cloud-policies/manage-prisma-cloud-policies.adoc
  docs/en/compute-edition/22-12/admin-guide/configure/permissions.adoc
  docs/en/compute-edition/30/admin-guide/configure/permissions.adoc
  docs/en/compute-edition/31/admin-guide/configure/permissions.adoc
  docs/en/compute-edition/32/admin-guide/configure/permissions.adoc
  docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-your-azure-account/microsoft-azure-apis-ingested-by-prisma-cloud.adoc
  docs/en/enterprise-edition/content-collections/dashboards/dashboards-code-to-cloud.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/configure/permissions.adoc
Labels: bug, documentation

#483 [Runtime Security] PCSUP-21922
  docs/en/compute-edition/32/rn/release-information/release-notes-32-00.adoc
Labels: documentation, O'Neal, awaiting-approval

#475 [Runtime Security] LA-PCEE O'Neal Update 4
  docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
Labels: do-not-merge, O'Neal Update 4

#485 [Runtime Security] Hotfix to RN- O'Neal
  docs/en/compute-edition/32/rn/release-information/release-notes-32-01.adoc
  docs/en/compute-edition/32/rn/release-information/release-notes-32-02.adoc
Labels: O'Neal

#497 note added for effective.action
  docs/en/enterprise-edition/content-collections/search-and-investigate/network-queries/network-config-query-attributes.adoc
Labels: documentation

#491 [Runtime Security]Update Defender upgrade blurb releases
  docs/en/compute-edition/32/rn/release-information/release-notes-32-00.adoc
  docs/en/compute-edition/32/rn/release-information/release-notes-32-01.adoc
  docs/en/compute-edition/32/rn/release-information/release-notes-32-02.adoc
  docs/en/compute-edition/32/rn/release-information/release-notes-32-03.adoc
Labels: bug, documentation

#504 [Runtime Security]Remove cost implication note in agentless scanning
  docs/en/classic/compute-admin-guide/agentless-scanning/agentless-scanning.adoc
  docs/en/compute-edition/32/admin-guide/agentless-scanning/agentless-scanning.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/agentless-scanning/agentless-scanning.adoc
Labels: bug, documentation, O'Neal Update 4

#357 [Runtime Security] Agentless Hosts Coverage Report
  docs/en/classic/compute-admin-guide/_graphics/agentless-aws-configuration.png
  docs/en/classic/compute-admin-guide/_graphics/agentless-azure-configuration.png
  docs/en/classic/compute-admin-guide/_graphics/agentless-gcp-pcee-advanced-settings.png
  docs/en/classic/compute-admin-guide/_graphics/agentless-hub-toggle.png
  docs/en/classic/compute-admin-guide/_graphics/agentless-scanning-results-1.png
  docs/en/classic/compute-admin-guide/_graphics/agentless-scanning-results-2.png
  docs/en/classic/compute-admin-guide/_graphics/agentless-scanning-results-3.png
  docs/en/classic/compute-admin-guide/agentless-scanning/agentless-scanning.adoc
  docs/en/classic/compute-admin-guide/agentless-scanning/onboard-accounts/configure-aws.adoc
  docs/en/classic/compute-admin-guide/agentless-scanning/onboard-accounts/configure-azure.adoc
  docs/en/classic/compute-admin-guide/agentless-scanning/onboard-accounts/configure-gcp.adoc
  docs/en/classic/compute-admin-guide/agentless-scanning/onboard-accounts/onboard-gcp.adoc
  docs/en/classic/compute-admin-guide/agentless-scanning/onboard-accounts/onboard-oci.adoc
  docs/en/classic/compute-admin-guide/book.yml
  docs/en/compute-edition/30/admin-guide/agentless-scanning/onboard-accounts/configure-gcp.adoc
  docs/en/compute-edition/31/admin-guide/agentless-scanning/onboard-accounts/configure-gcp.adoc
  docs/en/compute-edition/32/admin-guide/_graphics/agentless-gcp-pcee-advanced-settings.png
  docs/en/compute-edition/32/admin-guide/_graphics/agentless-hub-toggle.png
  docs/en/compute-edition/32/admin-guide/_graphics/agentless-scanning-results-1.png
  docs/en/compute-edition/32/admin-guide/_graphics/agentless-scanning-results-2.png
  docs/en/compute-edition/32/admin-guide/_graphics/agentless-scanning-results-3.png
  docs/en/compute-edition/32/admin-guide/agentless-scanning/agentless-scanning-results.adoc
  docs/en/compute-edition/32/admin-guide/agentless-scanning/agentless-scanning.adoc
  docs/en/compute-edition/32/admin-guide/agentless-scanning/onboard-accounts/configure-aws.adoc
  docs/en/compute-edition/32/admin-guide/agentless-scanning/onboard-accounts/configure-azure.adoc
  docs/en/compute-edition/32/admin-guide/agentless-scanning/onboard-accounts/configure-gcp.adoc
  docs/en/compute-edition/32/admin-guide/agentless-scanning/onboard-accounts/onboard-gcp.adoc
  docs/en/compute-edition/32/admin-guide/agentless-scanning/onboard-accounts/onboard-oci.adoc
  docs/en/enterprise-edition/content-collections/_graphics/runtime-security/agentless-gcp-pcee-advanced-settings.png
  docs/en/enterprise-edition/content-collections/_graphics/runtime-security/agentless-hub-toggle.png
  docs/en/enterprise-edition/content-collections/_graphics/runtime-security/agentless-scanning-results-1.png
  docs/en/enterprise-edition/content-collections/_graphics/runtime-security/agentless-scanning-results-2.png
  docs/en/enterprise-edition/content-collections/_graphics/runtime-security/agentless-scanning-results-3.png
  docs/en/enterprise-edition/content-collections/book.yml
  docs/en/enterprise-edition/content-collections/runtime-security/agentless-scanning/agentless-scanning-results.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/agentless-scanning/agentless-scanning.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/agentless-scanning/configure-accounts/configure-accounts.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/agentless-scanning/configure-accounts/configure-aws.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/agentless-scanning/configure-accounts/configure-azure.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/agentless-scanning/configure-accounts/configure-gcp.adoc
Labels: documentation, enhancement, O'Neal Update 1, awaiting-PM-approval

#518 [Runtime Security]Agentless small fixes
  docs/en/classic/compute-admin-guide/agentless-scanning/onboard-accounts/configure-aws.adoc
  docs/en/classic/compute-admin-guide/agentless-scanning/onboard-accounts/configure-azure.adoc
  docs/en/classic/compute-admin-guide/agentless-scanning/onboard-accounts/configure-gcp.adoc
  docs/en/compute-edition/32/admin-guide/agentless-scanning/onboard-accounts/configure-aws.adoc
  docs/en/compute-edition/32/admin-guide/agentless-scanning/onboard-accounts/configure-azure.adoc
  docs/en/compute-edition/32/admin-guide/agentless-scanning/onboard-accounts/configure-gcp.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/agentless-scanning/configure-accounts/configure-aws.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/agentless-scanning/configure-accounts/configure-azure.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/agentless-scanning/configure-accounts/configure-gcp.adoc
Labels: bug, documentation, awaiting-PM-approval, awaiting-approval

#519 24-3-2 rn
  docs/en/enterprise-edition/rn/24-1-2-rn-book.yml
  docs/en/enterprise-edition/rn/_graphics/Duns-n-domains-new-subscriber.png
  docs/en/enterprise-edition/rn/_graphics/cdem-network-flowlog-rn.png
  docs/en/enterprise-edition/rn/_graphics/cdem-snooze-rn.png
  docs/en/enterprise-edition/rn/_graphics/gcp-workspace.png
  docs/en/enterprise-edition/rn/book.yml
  docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
  docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-2024.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-march-2024.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/prisma-cloud-release-info.adoc
Labels: documentation, do-not-merge

#528 aws advanced settings ext id updates
  docs/en/enterprise-edition/content-collections/_graphics/connect/aws-add-account-2-1.png
  docs/en/enterprise-edition/content-collections/_graphics/connect/aws-add-account-global-org-2-1.png
  docs/en/enterprise-edition/content-collections/_graphics/connect/aws-update-stack-1.png
  docs/en/enterprise-edition/content-collections/_graphics/connect/edit-aws-account-2.png
  docs/en/enterprise-edition/content-collections/_graphics/connect/update-aws-org-1.png
  docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-aws/onboard-aws-account.adoc
  docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-aws/onboard-aws-org.adoc
  docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-aws/update-aws-account.adoc
  docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-aws/update-aws-org.adoc
  docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-aws/update-onboarded-aws-accnt-to-org.adoc
Labels: documentation

#506 O'Neal-Update4-PCEE-RN
  docs/en/enterprise-edition/rn/book.yml
  docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-compute-release-information/features-introduced-in-compute-march-2024.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-compute-release-information/prisma-cloud-compute-release-information.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-march-2024.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/prisma-cloud-release-info.adoc
Labels: do-not-merge

#541 [Runtime Security] O'Neal Update 4 -Patch update
  docs/en/compute-edition/32/rn/release-information/release-notes-32-04.adoc
  docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-compute-release-information/features-introduced-in-compute-march-2024.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-march-2024.adoc
Labels: O'Neal Update 4

#544 [Runtime Security] Patch for blurb CWP-56798
  docs/en/compute-edition/32/rn/release-information/release-notes-32-04.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/classic-releases/prisma-cloud-compute-release-information/features-introduced-in-compute-march-2024.adoc
Labels: O'Neal Update 4

#547 [Runtime Security] PCCE-Add Missed Addressed Issues
  docs/en/compute-edition/32/rn/book.yml
  docs/en/compute-edition/32/rn/release-information/release-notes-32-04.adoc
Labels: O'Neal Update 4
