Repository hlxsites/prisma-cloud-docs, pull requests merged in 2024-09, with the labels that each got.

#740 [CSPM Content Collections] Jira Integration 9.0
  docs/en/enterprise-edition/content-collections/_graphics/administration/Step-2-10.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/Step-2-11.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/Step-2-7.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/config-jira-9-0-1.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/config-jira-9-0-2.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/config-jira-9-0-3.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/config-jira-9-0-4.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/jira-integration-step-2-13.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/jira-integration-step-2-7.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/jira-success-below-9-0.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/secret-verification-1.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/secret-verification-2.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/setup-jira-9-0-1.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/setup-jira-9-0-2.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/setup-jira-9-0-3.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/setup-jira-9-0-4.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/setup-jira-9-0-5.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/setup-jira-9-0-6.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/setup-jira-9-0-7.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/setup-jira-9-0-8.png
  docs/en/enterprise-edition/content-collections/administration/configure-external-integrations-on-prisma-cloud/integrate-prisma-cloud-with-jira.adoc
Labels: documentation

#895 support lifecycle for 33.xx
  docs/en/compute-edition/33/admin-guide/upgrade/support-lifecycle.adoc
Labels: do-not-merge, awaiting-approval

#906 [CSPM RN] 9.2 release.
  docs/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-gcp/prerequisites-to-onboard-gcp.adoc
  docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-september-2024.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/prisma-cloud-release-info.adoc
Labels: documentation, do-not-merge, awaiting-approval

#913 Post 9.2 doc fixes
  docs/en/enterprise-edition/content-collections/alerts/view-respond-to-prisma-cloud-alerts.adoc
  docs/en/enterprise-edition/content-collections/governance/create-a-policy.adoc
  docs/en/enterprise-edition/rn/limited-ga-features-prisma-cloud/limited-ga-features-prisma-cloud.adoc
  docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
Labels: ready-to-be-merged
