Repository hlxsites/prisma-cloud-docs, pull requests merged in 2024-05, with the labels that each got.

#502 [Cloud Sec - Administration] cna fixes and updates
  docs/en/enterprise-edition/content-collections/_graphics/administration/alerts-w-cna.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/cloud-network-security-overview-2.png
  docs/en/enterprise-edition/content-collections/administration/collection-administration.yml
  docs/en/enterprise-edition/content-collections/administration/network-security/cloud-network-analyzer.adoc
  docs/en/enterprise-edition/content-collections/administration/network-security/investigate-network-exposure-on-prisma-cloud.adoc
  docs/en/enterprise-edition/content-collections/administration/network-security/network-security.adoc
  docs/en/enterprise-edition/content-collections/book.yml
  docs/en/enterprise-edition/content-collections/governance/create-a-network-policy.adoc
Labels: documentation, do-not-merge

#606 [Cloud Sec] Amazon Security Lake Integration
  docs/en/enterprise-edition/content-collections/_graphics/administration/integrate-amazon-security-lake-1.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/integrate-amazon-security-lake-2.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/integrate-amazon-security-lake-3.png
  docs/en/enterprise-edition/content-collections/_graphics/administration/integrate-amazon-security-lake-4.png
  docs/en/enterprise-edition/content-collections/administration/collection-administration.yml
  docs/en/enterprise-edition/content-collections/administration/configure-external-integrations-on-prisma-cloud/integrate-prisma-cloud-with-amazon-security-lake.adoc
  docs/en/enterprise-edition/content-collections/administration/configure-external-integrations-on-prisma-cloud/prisma-cloud-integrations.adoc
  docs/en/enterprise-edition/content-collections/book.yml
Labels: documentation, ready-to-be-merged

#451 [Runtime Security]Update Registry scanning content
  docs/en/enterprise-edition/content-collections/_graphics/runtime-security/gcr-add-registry.png
  docs/en/enterprise-edition/content-collections/_graphics/runtime-security/gitlab-container-registry.png
  docs/en/enterprise-edition/content-collections/_graphics/runtime-security/registry-scanning-webhooks.png
  docs/en/enterprise-edition/content-collections/_graphics/runtime-security/registry-scanning.png
  docs/en/enterprise-edition/content-collections/runtime-security/vulnerability-management/registry-scanning/configure-registry-scanning.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/vulnerability-management/registry-scanning/scan-gcr.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/vulnerability-management/registry-scanning/scan-gitlab.adoc
Labels: documentation, awaiting-PM-approval, awaiting-approval

#616 [Runtime Security] PCEE-RN-O'Neal Update 5
  docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
  docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-may-2024.adoc
Labels: O'Neal Update 5

#617 [Runtime Security] PCCE-RN-O'Neal Update 5
  docs/en/compute-edition/32/rn/book.yml
  docs/en/compute-edition/32/rn/book_point_release.yml
  docs/en/compute-edition/32/rn/release-information/release-notes-32-05.adoc
Labels: O'Neal Update 5

#630 [Cloud Sec] Expore Data - Node content fixes
  docs/en/enterprise-edition/content-collections/search-and-investigate/explore-data.adoc
Labels: do-not-merge

#624 [Runtime Security] Update 3 - Patch RN
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-february-2024.adoc
Labels: documentation, O'Neal Update 3

#638 [Runtime Security] Fix Syntax for CWP-55880
  docs/en/compute-edition/32/admin-guide/audit/review-debug-logs.adoc
  docs/en/enterprise-edition/content-collections/runtime-security/audit/review-debug-logs.adoc
Labels: O'Neal Update 5

#629 [Release Notes] - 24.5.2
  docs/en/enterprise-edition/rn/_graphics/identity-dashboard.gif
  docs/en/enterprise-edition/rn/_graphics/top-risks-from-unmanaged-assets.png
  docs/en/enterprise-edition/rn/known-issues/known-fixed-issues.adoc
  docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-may-2024.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/prisma-cloud-release-info.adoc
Labels: do-not-merge

#639 [Runtime Security] LA - O'Neal Update 6 (Pascal)
  docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-runtime.adoc
Labels: do-not-merge, O'Neal Update 6 (Pascal)

#642 [LA 24.6.1] LM updates
  docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
Labels: do-not-merge, awaiting-PM-approval

#650 6-1-RN
  docs/en/enterprise-edition/rn/_graphics/account-mapped-status.png
  docs/en/enterprise-edition/rn/_graphics/snooze-assets.png
  docs/en/enterprise-edition/rn/_graphics/top-risks-from-unmanaged-assets-widget.png
  docs/en/enterprise-edition/rn/_graphics/vulnerabilities-tab.gif
  docs/en/enterprise-edition/rn/book.yml
  docs/en/enterprise-edition/rn/draft-book.yaml
  docs/en/enterprise-edition/rn/look-ahead-planned-updates-prisma-cloud/look-ahead-secure-the-infrastructure.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-2024.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-june-2024.adoc
  docs/en/enterprise-edition/rn/prisma-cloud-release-info/features-introduced-in-2024/features-introduced-in-may-2024.adoc
Labels: do-not-merge
